"""Fetch GitHub stars/forks for ``open_source_projects.yaml``; write ``open_source_github_stats.yaml``."""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

from greek_software_ecosystem.github_stars import (
    fetch_github_repo_stats,
    parse_github_repo_url,
)

_REPO_ROOT = Path(__file__).resolve().parents[2]
OPEN_SOURCE_PROJECTS_YAML = _REPO_ROOT / "_data" / "open_source_projects.yaml"
OSS_STATS_YAML = _REPO_ROOT / "_data" / "open_source_github_stats.yaml"


def _repo_key(url: str) -> str | None:
    p = parse_github_repo_url((url or "").strip())
    if not p:
        return None
    owner, repo = p
    return f"{owner}/{repo}"


def run_fetch() -> int:
    if not OPEN_SOURCE_PROJECTS_YAML.is_file():
        print(f"Missing {OPEN_SOURCE_PROJECTS_YAML}", file=sys.stderr)
        return 1
    try:
        with OPEN_SOURCE_PROJECTS_YAML.open(encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
    except (yaml.YAMLError, OSError) as e:
        print(f"Failed to read projects YAML: {e}", file=sys.stderr)
        return 1
    projects = data.get("projects") if isinstance(data, dict) else None
    if not isinstance(projects, list):
        print("No projects list in open_source_projects.yaml", file=sys.stderr)
        return 1

    keys_in_order: list[str] = []
    seen: set[str] = set()
    for p in projects:
        if not isinstance(p, dict):
            continue
        url = (p.get("url") or "").strip()
        if not url:
            continue
        key = _repo_key(url)
        if not key or key in seen:
            continue
        seen.add(key)
        keys_in_order.append(key)

    total = len(keys_in_order)
    print(
        f"Fetching GitHub stars/forks for {total} repositories…",
        file=sys.stderr,
        flush=True,
    )

    out_repos: dict[str, dict[str, int | bool | None]] = {}
    archived_count = 0
    for i, key in enumerate(keys_in_order, start=1):
        owner, _, repo = key.partition("/")
        if not repo:
            continue
        stars, forks, archived = fetch_github_repo_stats(owner, repo)
        is_archived = bool(archived)
        if is_archived:
            archived_count += 1
        out_repos[key] = {
            "stars": stars,
            "forks": forks,
            "archived": is_archived,
        }
        if total >= 15 and (i == 1 or i == total or i % 25 == 0):
            print(f"  Progress: {i}/{total}…", file=sys.stderr, flush=True)

    payload = {
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "repos": out_repos,
    }
    gen_cmd = "uv run python -m greek_software_ecosystem.fetch_open_source_github_stats"
    header = (
        f"# Auto-generated by: {gen_cmd}\n"
        "# Do not edit by hand. Regenerate after changing open_source_projects.yaml.\n\n"
    )
    OSS_STATS_YAML.parent.mkdir(parents=True, exist_ok=True)
    OSS_STATS_YAML.write_text(
        header + yaml.safe_dump(payload, allow_unicode=True, sort_keys=False),
        encoding="utf-8",
    )
    print(f"Wrote {OSS_STATS_YAML} ({total} repos, {archived_count} archived).", file=sys.stderr)
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Read open_source_projects.yaml, call the GitHub API per repo, "
            "and write open_source_github_stats.yaml for generate_index / readme."
        ),
    )
    parser.parse_args(argv)
    return run_fetch()


if __name__ == "__main__":
    raise SystemExit(main())
